name: 'Setup Submodules'
description: 'A custom action to setup git submodules'
inputs:
  recursive:
    description: 'Whether to recursively update submodules'
    required: true
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Initialize submodules
      run: git submodule update --init --recursive
      shell: bash
